# Generated by Django 5.2.7 on 2025-10-23 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employer', 'Employer'), ('worker', 'Worker')], default='worker', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(blank=True, choices=[('almaty', 'Алматы'), ('astana', 'Астана'), ('shymkent', 'Шымкент'), ('karaganda', 'Караганда'), ('pavlodar', 'Павлодар'), ('semey', 'Семей'), ('aktau', 'Актау'), ('aktobe', 'Актобе'), ('atyrau', 'Атырау'), ('kostanay', 'Костанай'), ('kokshetau', 'Кокшетау'), ('taraz', 'Тараз'), ('uralsk', 'Уральск'), ('petropavlovsk', 'Петропавловск'), ('temirtau', 'Темиртау'), ('taldykorgan', 'Талдыкорган'), ('jezkazgan', 'Жезказган'), ('ekibastuz', 'Экибастуз'), ('kzylorda', 'Кызылорда'), ('ust-kamenogorsk', 'Усть-Каменогорск'), ('zhanaozen', 'Жанаозен'), ('turan', 'Туран')], max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
