# Generated by Django 5.2.7 on 2025-11-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_order_orderapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('worker', 'Worker')], max_length=10),
        ),
    ]
