# Generated by Django 5.2.7 on 2025-12-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='job_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
